### ISSUE TITLE
Installation on OS X

### ISSUE THREAD

**Issue by larstvei** [expertanalytics/cvcreator#2]
Hi!

I tried installing this on OS X, but ran into a problem when installing `pyyaml`. [This stackoverflow post](http://stackoverflow.com/questions/25970966/setup-pyyaml-with-pyenv-on-mac-os-x-file-not-found-python-exe) led me to the following solution:

```
CC=$(which python) pip install pyyaml
```

Perhaps it would be an idea to add this to the README.

**Comment by jonathf** [comment]
Agreed.

Thanks for tip. I've updated the README file.

**Comment by larstvei** [comment]
Great!

Something happened with the formatting though; I think the tildes should be replaced with dashes.

**Comment by jonathf** [comment]
Absolutely. I was writing in rst on autopilot. Forgot it was md. :)
