### ISSUE TITLE
Moving meta-info out of the way

### ISSUE THREAD

**Issue by jonathf** [expertanalytics/cvcreator#47]
Personal preference perhaps, but I think the first section in our CVs (address, phone, etc.) are not really part of the CV, and should be moved out of the way,

Something like this where it is moved up to the left corner, icons instead of text and with a smaller font size:
[feinberg2.pdf](https://github.com/expertanalytics/cvcreator/files/6549024/feinberg2.pdf)

Is this something that makes sense to more than just me?

**Comment by kememil** [comment]
I think this looks very nice :)
Is the order of the fields something to consider as well? Is the contact info most relevant for the reader, or the address and birth date?

**Comment by jonathf** [comment]
That is a good point. I've reordered them now so that address and birth date at the bottom.

**Comment by jonathf** [comment]
See example in the description of #48.

**Comment by mandus** [comment]
Agree that it is nice to separate the personal info from the other content - your suggestion is nice; but not certain about the icon selected for date of birth - you kind of have to guess that the calendar entry relates to age (of course, what else can it be - but still not immediately obvious what it is...)

As for order of fields, I suggest email / phone / date of birth / address - address is the least interesting part here I'll say.

**Comment by jonathf** [comment]
Sounds good.

I agree the birthday icon is bad. How about this:
[birthday.pdf](https://github.com/expertanalytics/cvcreator/files/6553211/birthday.pdf)

**Comment by mandus** [comment]
(according to google, the one you suggested seems to be somewhat recognized as DoB...)
